global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          alias: "cadvisor"
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          alias: "grafana"
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
        labels:
          alias: "node_exporter"
